CREATE TABLE IF NOT EXISTS accounts (
    id SERIAL PRIMARY KEY,
    userId VARCHAR(255) UNIQUE NOT NULL,
    contractCode VARCHAR(255) NOT NULL,
    accountReference VARCHAR(255) NOT NULL,
    accountNumber VARCHAR(255) NOT NULL,
    accountName TEXT NOT NULL,
    bankName VARCHAR(255) NOT NULL,
    bankCode INTEGER NOT NULL,
    currencyCode VARCHAR(255) NOT NULL,
    customerName TEXT NOT NULL,
    customerEmail UNIQUE TEXT NOT NULL,
    accountBalance DECIMAL(10, 4) NOT NULL DEFAULT 0.00,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)