# Generated by Django 5.2.3 on 2025-06-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="school_id",
            field=models.CharField(max_length=255),
        ),
    ]
