[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = ["legacy-cgi>=2.6.3", "pygen>=0.0.2", "requests>=2.9.1", "urllib3>=2.4.0"]
